version: '3.8'

services:
  nginx:
    image: ghcr.io/wunderbald/nginx-quic:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # Required for QUIC
    depends_on:
      - auth_service
    networks:
      - app-network

  auth_service:
    build: ./auth_service
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
