
services:
  editor_mongodb:
    container_name: editor_mongodb
    image: mongo
    ports:
      - "27017"
    volumes:
      - editor-mongodb-volume:/data/db
    networks:
      - app-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  editor_documentation_service:
    container_name: editor_documentation_service
    image: documentation_service:v1.0
    ports:
      - "3004:3004"
    depends_on:
      - editor_mongodb
    environment:
      - MONGO_HOST=editor_mongodb
      - MONGO_PORT=27017
    env_file:
      - .env.docker
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

networks:
  app-network:

volumes:
  editor-mongodb-volume: