
services:

  editor-nginx:
    container_name: editor-nginx
    image: editor_nginx:v1.0
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - app-network

  editor-mongodb:
    container_name: editor-mongodb
    image: mongo
    ports:
      - "27017"
    networks:
      - app-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  editor-rabbitmq:
    container_name: editor-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672"
      - "15672"
    networks:
      - app-network

  editor-payment-service:
    container_name: editor-payment-service
    image: payment_service:v1.0
    ports:
      - "3002:3002"
    depends_on:
      - editor-mongodb
      - editor-rabbitmq
    environment:
      - MONGO_HOST=editor-mongodb
      - MONGO_PORT=27017
      - RABBITMQ_HOST=editor-rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

  editor-documentation-service:
    container_name: editor-documentation-service
    image: documentation_service:v1.0
    ports:
      - "3004:3004"
    depends_on:
      - editor-mongodb
    environment:
      - MONGO_HOST=editor-mongodb
      - MONGO_PORT=27017
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

  editor-auth-service:
    container_name: editor-auth-service
    image: auth_service:v1.0
    ports:
      - "3000:3000"
    depends_on:
      - editor-mongodb
      - editor-rabbitmq
    environment:
      - MONGO_HOST=editor_mongodb
      - MONGO_PORT=27017
      - RABBITMQ_HOST=editor-rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

  editor-agent-service:
    container_name: editor-agent-service
    image: agent_service:v1.0
    ports:
      - "3001:3001"
      - "4001:4001"
    depends_on:
      - editor-mongodb
      - editor-rabbitmq
    environment:
      - MONGO_HOST=editor-mongodb
      - MONGO_PORT=27017
      - RABBITMQ_HOST=editor-rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

  editor-email-service:
    container_name: editor-email-service
    image: email_service:v1.0
    ports:
      - "3006:3006"
    depends_on:
      - editor-mongodb
      - editor-rabbitmq
    environment:
      - MONGO_HOST=editor-mongodb
      - MONGO_PORT=27017
      - RABBITMQ_HOST=editor-rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

  editor-embedding-service:
    container_name: editor-embedding-service
    image: embedding_service:v1.0
    ports:
      - "3003:3003"
    networks:
      - app-network

  editor-rag-evaluation-service:
    container_name: editor-rag-evaluation-service
    image: rag_evaluation_service:v1.0
    ports:
      - "3005:3005"
    networks:
      - app-network

  editor-app-client:
    container_name: editor-app-client
    image: app_client:v1.0
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
