
services:

  editor_app_client:
    container_name: editor_app_client
    image: app_client:v1.0
    ports:
      - "5174:5174"
    env_file:
      - .env.docker
    networks:
      - app-network

networks:
  app-network:
