
services:
  editor_mongodb:
    container_name: editor_mongodb
    image: mongo
    ports:
      - "27017"
    volumes:
      - editor-mongodb-volume:/data/db
    networks:
      - app-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  editor_rabbitmq:
    container_name: editor_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672"
      - "15672"
    networks:
      - app-network

  editor_email_service:
    container_name: editor_email_service
    image: email_service:v1.0
    ports:
      - "3006:3006"
    depends_on:
      - editor_mongodb
      - editor_rabbitmq
    environment:
      - MONGO_HOST=editor_mongodb
      - MONGO_PORT=27017
      - RABBITMQ_HOST=editor_rabbitmq
      - RABBITMQ_PORT=5672
    env_file:
      - .env.docker
    networks:
      - app-network
    command: ["sh", "wait_for_start.sh"]

networks:
  app-network:

volumes:
  editor-mongodb-volume: