name: Deploy App Desktop

on:
  push:
    tags:
      - "editor-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create .env file
        run: |
          cd ./app_desktop
          echo "${{ secrets.APP_DESKTOP_ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          cd ./app_desktop
          npm install

      - name: Remove .env file
        run: |
          cd ./app_desktop
          rm .env

 
  release-linux:
    needs: 
      - build
      #- test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          cd ./app_desktop
          echo "${{ secrets.APP_DESKTOP_ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          cd ./app_desktop
          npm install

      - name: Build Electron app (Linux)
        run: |
          cd ./app_desktop
          npm run build

      - name: Publish Linux release
        run: |
          cd ./app_desktop
          npm exec electron-builder -- --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-macos:
    needs: 
      - build
      #- test
    runs-on: macos-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          cd ./app_desktop
          echo "${{ secrets.APP_DESKTOP_ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          cd ./app_desktop
          npm install
          npm i sqlite-vec-darwin-x64

      - name: Build Electron app (macOS)
        run: |
          cd ./app_desktop
          npm run build

      - name: Publish macOS release
        run: |
          cd ./app_desktop
          npm exec electron-builder -- --mac --x64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-windows:
    needs: 
      - build
      #- test
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          cd ./app_desktop
          echo "${{ secrets.APP_DESKTOP_ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          cd ./app_desktop
          npm install

      - name: Build Electron app (Windows)
        run: |
          cd ./app_desktop
          npm run build

      - name: Publish Windows release
        run: |
          cd ./app_desktop
          npm exec electron-builder -- --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
