name: Deploy App Desktop

on:
  push:
    tags:
      - 'editor-v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ./app_desktop
          npm install

      - name: Install snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install snapcraft --classic

      - name: Build Electron app
        run: |
          cd ./app_desktop
          npm run build

      - name: Publish release
        run: |
          cd ./app_desktop
          npm exec electron-builder -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
