name: Deploy Email Service

on:
  push:
    branches:
      - release-email-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: | 
          cd ./email_service
          echo "${{ secrets.EMAIL_ENV_FILE }}" > .env    

      - name: Install dependencies
        run: | 
          cd ./email_service
          npm install

      - name: Remove .env file
        run: |
          cd ./email_service
          rm .env
  
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      MONGO_HOST: 127.0.0.1 
      RABBITMQ_HOST: 127.0.0.1
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672  
          - 15672:15672 
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # https://engineering.synatic.com/a-simple-way-to-run-a-mongodb-replica-set-in-github-actions
      - name: Start mongo
        id: start-mongo
        run: docker run --rm -d -p 27017:27017 --name mongo  mongo:4.4.9 --replSet test --bind_ip_all
      - name: Initialize MongoDB Replica Set
        run: |
          sleep 5 # Give mongo a chance to start up
          docker run --rm mongo:6.0 mongosh --host 172.17.0.1 --eval 'rs.initiate({_id: "test", members: [{_id: 0, host: "172.17.0.1:27017"}]})'

      - name: Create .env file
        run: |
          cd ./email_service
          echo "${{ secrets.EMAIL_TEST_ENV_FILE }}" > .env   

      - name: Install mongosh
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Install dependencies
        run: |
          cd ./email_service
          npm install
        
      - name: Wait for dependencies (mongodb and rabbitmq)
        run: |
          cd ./email_service
          sh ./wait_for_dependencies.sh

      - name: Run tests
        run: |
          cd ./email_service
          npm test  

      - name: Remove .env file
        run: |
          cd ./email_service
          rm .env
         
  deploy:
    needs: 
      - build
      - test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          cd ./email_service
          echo "${{ secrets.EMAIL_ENV_FILE }}" > .env

    - name: Create Gmail credentials file
      run: |
          cd ./email_service
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > gmail_credentials.json

    - name: Create Gmail token file
      run: |
          cd ./email_service
          echo "${{ secrets.GMAIL_TOKEN }}" > gmail_token.json

    - name: SSH and Remove old files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ${{ secrets.SERVER_LOCATION }}/github/workspace/email_service
    
    - name: SCP files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "${{ secrets.SERVER_HOST }}"
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "${{ github.workspace }}/email_service"
        target: "${{ secrets.SERVER_LOCATION }}"
    
    - name: SSH and Docker build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.SERVER_LOCATION }}/github/workspace/email_service
          docker build -t ${{ secrets.EMAIL_IMAGE_NAME }}:${{ secrets.EMAIL_IMAGE_TAG }} .
          docker image prune -f
          k3d image import ${{ secrets.EMAIL_IMAGE_NAME }}:${{ secrets.EMAIL_IMAGE_TAG }}
          cd ${{ secrets.SERVER_LOCATION }}
          ./kubectl get pods | grep email-service | awk '{print $1}' | xargs ./kubectl delete pod
    
    - name: Remove .env file
      run: |
          cd ./email_service
          rm .env

    - name: Remove Gmail credentials file
      run: |
          cd ./email_service
          rm gmail_credentials.json

    - name: Remove Gmail token file
      run: |
          cd ./email_service
          rm gmail_token.json
