name: Deploy Nginx

on:
  push:
    branches:
      - release-nginx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: SCP files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "${{ secrets.SERVER_HOST }}"
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "${{ github.workspace }}/nginx"
        target: "${{ secrets.SERVER_LOCATION }}"
    
    - name: SSH and Docker build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.SERVER_LOCATION }}/github/workspace/nginx
          docker build -t ${{ secrets.NGINX_IMAGE_NAME }}:${{ secrets.NGINX_IMAGE_TAG }} .
          docker image prune -f
          k3d image import ${{ secrets.NGINX_IMAGE_NAME }}:${{ secrets.NGINX_IMAGE_TAG }}
    